/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.billpay;

/**
 *
 * @author weth767
 */
public class BillPayConsult extends javax.swing.JInternalFrame {

    /**
     * Creates new form BillReceiveConsult
     */
    public BillPayConsult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFilter = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnPayBill = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billPaysTable = new javax.swing.JTable();
        labelFilter = new javax.swing.JLabel();
        comboBillReceive = new javax.swing.JComboBox<>();

        setTitle("Consulta de Contas à Pagar");
        setToolTipText("Tela de Consulta de Contas à Pagar");

        btnSearch.setText("Consultar");

        btnPayBill.setText("Pagar Conta");
        btnPayBill.setToolTipText("Retornar dados para a tela de Pagar Conta");

        btnCancel.setText("Cancelar");
        btnCancel.setToolTipText("Cancelar Operação");

        billPaysTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NF", "CNPJ Fornecedor", "Data de Vencimento", "Valor da Parcela", "Parcelas Restantes", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billPaysTable);
        if (billPaysTable.getColumnModel().getColumnCount() > 0) {
            billPaysTable.getColumnModel().getColumn(0).setResizable(false);
            billPaysTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            billPaysTable.getColumnModel().getColumn(1).setResizable(false);
            billPaysTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            billPaysTable.getColumnModel().getColumn(2).setResizable(false);
            billPaysTable.getColumnModel().getColumn(2).setPreferredWidth(130);
            billPaysTable.getColumnModel().getColumn(3).setResizable(false);
            billPaysTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            billPaysTable.getColumnModel().getColumn(4).setResizable(false);
            billPaysTable.getColumnModel().getColumn(4).setPreferredWidth(130);
            billPaysTable.getColumnModel().getColumn(5).setResizable(false);
            billPaysTable.getColumnModel().getColumn(5).setPreferredWidth(70);
        }

        labelFilter.setText("Filtro");

        comboBillReceive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NF", "Data de Vencimento" }));
        comboBillReceive.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(labelFilter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBillReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(btnPayBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilter)
                    .addComponent(comboBillReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayBill)
                    .addComponent(btnCancel))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billPaysTable;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboBillReceive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFilter;
    private javax.swing.JTextField textFilter;
    // End of variables declaration//GEN-END:variables
}
